# Generated by Django 4.1 on 2025-11-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90)),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateTimeField()),
                ('destaque', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='4', max_length=5)),
                ('foto', models.CharField(max_length=60)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias_autor', to='noticias.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias_categoria', to='noticias.categoria')),
            ],
        ),
    ]
