# Generated by Django 4.1 on 2025-11-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
